### ISSUE TITLE
Validate front matter as a valid Schema.org schema

### ISSUE THREAD

**Issue by johnfraney** [blurry-dev/blurry#26]
Blurry front matter is designed to use [Schema.org](https://schema.org/) schemas as their front matter for SEO. We can validate that front matter matches a Schema.org type to find missing/extra fields and communicate that in the CLI.

One possible library we could use for those types: https://github.com/lexiq-legal/pydantic_schemaorg

**Comment by KajKandler** [comment]
As a matter of fact the current version does not pass https://validator.schema.org/ by default. There is an invalid property "pathname" (for something like webpage). Is there a way to suppress this?

**Comment by johnfraney** [comment]
> There is an invalid property "pathname" (for something like webpage). Is there a way to suppress this?

Ah! That's a bug, then. It should be available in the template context but not included in the schema. Are you able to open a big for that? If not I should be able to this evening.

**Comment by KajKandler** [comment]
Yeah, I can do that!

Am Di., 14. Nov. 2023 um 15:10 Uhr schrieb John Franey <
***@***.***>:
