### ISSUE TITLE
Global schema data is not auto-updated

### ISSUE THREAD

**Issue by KajKandler** [blurry-dev/blurry#32]
Working on a project with much of the global schema, it is painful that the data is kept in the blurry.toml file which is only read once on server startup.

It would be really helpful to have global schema in a file in the content area so that the file is watched and auto updated by the server.

**Comment by johnfraney** [comment]
It would be good for this to auto-update for sure. I'm trying out a couple different ways of doing this, and one of them is looking pretty promising:

https://github.com/blurry-dev/blurry/assets/1728528/3ba914f4-8063-4f12-98bf-5b742e6c0d23
