### ISSUE TITLE
Support flexible extensions for templates

### ISSUE THREAD

**Issue by KajKandler** [blurry-dev/blurry#33]
I have a project, where I want to create other templates, that are not HTML. Besides, I prefer to name my Jinja templates `.html.jinja2` or similar in order to get dedicated support in my code editor for the format 'html+jinja2'

Furthermore I have templates that are not for HTML, such as XML, SVG, or a simple robots.txt

It would be desirable to have a flexible templating file extension. For example a list in config that is searched for until a template is found.

This point might be moot, if you'd separate the @type from the ~template attribute or allow a ~template overwrite for the @type. - That way I can spec the full name of the template and the whole system would be more flexible (including files that have no schema, such as SVG, XML and robots.txt)

**Comment by johnfraney** [comment]
Okay, I'm taking a crack at this. Would you be able to open a separate issue for processing other files? That's a bit more effort so I don't want it to hold up the custom template extensions

**Comment by KajKandler** [comment]
> Okay, I'm taking a crack at this. Would you be able to open a separate issue for processing other files? That's a bit more effort so I don't want it to hold up the custom template extensions

I created https://github.com/blurry-dev/blurry/issues/44
