### ISSUE TITLE
sourceOrganization breaks schema validation

### ISSUE THREAD

**Issue by KajKandler** [blurry-dev/blurry#36]
When I follow the prescriptive blurry.toml and define a `blurry.schema.data.sourceOrganization` I get a schema validation error in schema.org Validator.

![Screenshot 2023-11-16 at 8 40 26 PM](https://github.com/blurry-dev/blurry/assets/411504/a6c17af2-436a-44f8-96ef-d231a4f2dada)

Not defining the sourceOrganization breaks the Open Graph support.

Suggestion, configure in blurry.toml a template that creates the og support and supply a sample template. That makes it configurable if one wants to include og support and how. It also makes it easy to extend to Xwitter support (Facebook is deprecated and probably not something to implement in 2023).

XWitter = X/Twitter

**Comment by KajKandler** [comment]
In addition this causes a double type in schema
![Screenshot 2023-11-16 at 8 49 15 PM](https://github.com/blurry-dev/blurry/assets/411504/34a9f4b3-8f9a-4e71-b435-6ef727d00bfc)

If one gives the source organization a type, because it would make sense to  use this element as a publisher attribute.

**Comment by johnfraney** [comment]
@KajKandler Thanks for the report. Could I see the relevant part of your `blurry.toml` file? I've got this in the docs site and it looks to be working well:

```toml
[blurry.schema_data.sourceOrganization]
name = 'Blurry'
```

![image](https://github.com/blurry-dev/blurry/assets/1728528/87561a09-ffa9-4740-92bb-ae8b9e27b59c)

https://validator.schema.org/#url=https%3A%2F%2Fblurry-docs.netlify.app%2F

**Comment by KajKandler** [comment]
```
[blurry.schema_data.sourceOrganization]
"@type" = "Person"
"@id" = "https://janedoe.example.com/"
name = "Jane Doe"
url = "https://janedoe.example.com/"
```

Maybe it is because of my 'organization' being of type Person

**Comment by KajKandler** [comment]
![Screenshot 2023-11-24 at 10 55 46 AM](https://github.com/blurry-dev/blurry/assets/411504/b6359289-fbe4-416b-9ea7-4597b873221a)


Confirmed it does not like 'Person' as sourceOrganization.

**Comment by KajKandler** [comment]
I guess this is resolved
