### ISSUE TITLE
Support other file types besides .html

### ISSUE THREAD

**Issue by KajKandler** [blurry-dev/blurry#44]
The generator has built in assumptions about all generated files being MD --> HTML.

However a website may have other files such as XML, SVG, or a simple robots.txt

It is desirable to support other formats as well with the data from schema (probably not quite with the markdown to content)

**Comment by johnfraney** [comment]
@KajKandler Sorry for the delay on this one, but I had some time today and got this working nicely. I'm getting a new release together now!
