### ISSUE TITLE
Markdown image processing is missing alt-text

### ISSUE THREAD

**Issue by KajKandler** [blurry-dev/blurry#45]
A Markdown like 
```
![Alt Text](./media/foo.img "A Photo of foo")
```

 is supposed to be translated into 

```
<img src="./media/foo.img" alt="Alt Text" title="A Phtoto of foo" />
```

But the `alt` attribute is not filled and leads to an HTML syntax violation, as it is required on an `<img>` tag.

## Example
![A photo of the Foo Fighters (rock band) against a white background](https://www.rockantenne.de/media/cache/3/version/2733/140735_foo_fighters_concrete_and_gold_2017_05_sony_1500.011c6919-v2.jpg/8b5d5123ddcfcff33e24bf996dcc4216.webp)

**Comment by johnfraney** [comment]
I wonder if the title handling is the issue here. Alt text is working nicely in my blog, for instance:

![image](https://github.com/blurry-dev/blurry/assets/1728528/a1105f30-5ef9-426f-a698-781f49afa2eb)

**Comment by KajKandler** [comment]
My point is that the title is not supported. 

I'd also see a title more like a caption. Because an alt text is supposed to explain the image content to a blind person, which is usually too verbose for a caption of an image.
